main/urls.py
from django.urls import path
from main.views import *

app_name = "main"

urlpatterns = [
    path("", home, name="home"),
    path("customer/", customer_page, name="customer_page"),
    path("courier/", courier_page, name="courier_page"),
    path("sign-up/", sign_up, name="sign_up"),
]

parcelapp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("sign-in/", auth_views.LoginView.as_view(template_name="sign_in.html")),
    path("sign-out/", auth_views.LogoutView.as_view(next_page="/")),
]

main/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.forms import fields


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=250)
    first_name = forms.CharField(max_length=250)
    last_name = forms.CharField(max_length=250)

    class Meta:
        model = User
        fields = ("email", "first_name", "last_name", "password1", "password2")

    def clean_email(self):
        """Checking email address exists"""
        email = self.cleaned_data["email"].lower()
        if User.objects.filter(email=email):
            raise ValidationError("This email address already exists.")
        return email

main/views.py
from django.contrib.auth import login
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from .forms import SignUpForm


@login_required
def home(request):
    template = "home.html"
    return render(request, template)


@login_required
def customer_page(request):
    template = "home.html"
    return render(request, template)


@login_required
def courier_page(request):
    template = "home.html"
    return render(request, template)


def sign_up(request):
    template = "sign_up.html"
    form = SignUpForm()
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("email").lower()
            user = form.save(commit=False)
            user.username = email
            user.save()

            login(request, user)
            return redirect("/")

    return render(request, template, {"form": form})

main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% comment %} load the bootstrap tag library {% endcomment %}
    {% load bootstrap4 %}

    {% comment %} load bootstrap css and javascript {% endcomment %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>
<body>
<nav class="navbar  navbar-dark navbar-expand-lg fixed-top bg-dark">
  <a class="navbar-brand" href="{% url 'main:home' %}">DjangoParcelApp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  {% if not request.user.is_authenticated %}
    <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <a class="nav-link" href="{% url 'main:customer_page' %}">Customer</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main:courier_page' %}">Courier</a>
      </li>

    </ul>
  </div>
  {% else %}
    <form action="" class="form-inline">
      <span class="text-white mr-2">{{ request.user.username }}</span>
      <a href="/sign-out/" class="btn btn-light">Sign Out</a>
    </form>
  {% endif %}

</nav>
<div class="container-fluid mt-5">
{% block content %}{% endblock %}
</div>

<footer class="mb-5 mt-5 text-center">
 &copy;vinod
</footer>
</body>
</html>

main/templates/home.html
{% extends 'base.html' %}
{% block title %}
  Home Page
{% endblock title %}
{% block content %}
  <div class="container">
    <div class="col-md-12 col-lg-12 col-12 p-3 mt-5">
      <div class="row">
        <div class="col-sm-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Coustomer</h5>
              <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
              <a href="{% url 'main:customer_page' %}" class="btn btn-primary">Details</a>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Courier</h5>
              <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
              <a href="{% url 'main:courier_page' %}" class="btn btn-primary">Details</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock  %}

main/templates/sign_in.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Sign In{% endblock title %}
{% block content %}
    <div class="container-fluid ">
        <div class="row justify-content-center ">
            <div class="col-lg-4 mt-4">
                <div class="card ">
                    <div class="card-header text-center">
                        <h4>
                        {% if request.GET.next != '/courier/' %}
                            <strong >Customer</strong>
                        {% else %}
                            <strong >Courier</strong>
                        {% endif %}

                        </h4>
                    </div>
                    <div class="card-body">

                        <div class="mt-4">
                            <form action="" method="POST">
                                {% csrf_token %}

                                {% bootstrap_form_errors form %}
                                {% bootstrap_label "Email" %}
                                {% bootstrap_field form.username show_label=False  placeholder="Email" %}
                                {% bootstrap_field form.password %}

                            <button type="submit" class="btn btn-primary btn-block">Sign In</button>
                            </form>

                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
{% endblock content %}

main/templates/sign_up.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Sign Up{% endblock title %}
{% block content %}
    <div class="container-fluid ">
        <div class="row justify-content-center ">
            <div class="col-lg-4 mt-4">
                <div class="card ">
                    <div class="card-header text-center">
                        <h4>
                        {% if request.GET.next != '/courier/' %}
                            <strong >Customer</strong>
                        {% else %}
                            <strong >Courier</strong>
                        {% endif %}

                        </h4>
                    </div>
                    <div class="card-body">

                        <div class="">
                            <form method="POST">
                                {% csrf_token %}

                                {% bootstrap_form_errors form %}
                                {% bootstrap_form form %}

                            <button type="submit" class="btn btn-primary btn-block">Sign Up</button>
                            </form>

                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
{% endblock content %}